### ISSUE TITLE
PULL REQUEST TEMPLATE

### ISSUE THREAD

**Issue by edilsalvador** [tekilinux/TekiLinux-amd64#2]
Hi @christianwico,
After looking at your pull request template, I guess it's a bit cluttered.

As a suggestion, maybe you could omit the following:
- Motivation and Context
- How Has This Been Tested
- Screenshots
- Types of changes

I think all we need to include are:
- Brief Description of the Pull Request
- Changes Included
- Relevant Issues (if any)
- Place to start (for the reviewer)

And also refer the Issue number and the branch link of the pull request.
I guess our development flow could be as simple as this: [Basic GitFLow](https://guides.github.com/introduction/flow/)
So that everyone could easily get along with our project and everything will be separated from the repository.

┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;tekilinux&#x2F;TekiLinux-amd64&#x2F;issues&#x2F;2">#2 PULL REQUEST TEMPLATE</a>

**Comment by apquinit** [comment]
wala tayong magiging naming convention sa branch, justthe issue number, pag may need gawin open lang ng issue. gawa lang tayo ng issue tags by using this standard: https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

**Comment by edilsalvador** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#2 ⁃ PULL REQUEST TEMPLATE](https://trello.com/c/8pxq4gzm/1-2-pull-request-template)
